### ISSUE TITLE
webOS 상에서의 mediapipe 지원 문제

### ISSUE THREAD

**Issue by jjunh33** [webOS-KOSS/main-HomeTraining#1]
MediaPipe 에서 사용하는 tensorflow API 는 webassembly (WASM) 으로 구현되어 있는데, webOS OSE는 WASM을 지원하지 않기 때문에 MediaPipe JavaScript Solution 이 동작하지 않음
->python 파일을 webOS에 올리고 webApp에서 이를 실행시키는 형식으로 구현해야 할 듯
-> 그렇다면 어느 부분까지 python으로 구현할 지 생각해야 함

**Comment by ymw0407** [comment]
현재 mediapipe js가 webOS상에서 돌아가지 않는다는 답변을 받았다.
현재 생각나는 해결방법으로는

1. 파이썬을 이식해보는 방법
2. 도커를 사용하여 mediapipe를 사용할 수 있게 만드는 것
이렇게 2가지 이다. 해당 방법을 시도해볼 것이다.

**Comment by ymw0407** [comment]
@jjunh33 이가 mediapipe python을 성공함, 따라서 상당수 부분이 해결되었음
하지만 한 카메라로 webOS의 웹앱과 python에서 각각 사용할 수 없다는 문제가 발생함
해당 문제를 해결하기 위한 방법이 필요하다고 보임

**Comment by ymw0407** [comment]
node js의 childprocess라는 node module을 사용하여 python을 비동기적으로 실행시키는 방법을 채택하였다.
